version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./rate_limit.conf:/etc/nginx/conf.d/rate_limit.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/staticfiles:ro
    networks:
      - nomade_net

volumes:
  static_volume:
    external: true
  
networks:
  nomade_net:
    external: true
